services:
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - plex-listen-brainz
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-local.my-test-job.schedule: "@every 5s"
      ofelia.job-local.my-test-job.command: "date"

  plex-listen-brainz:
    build: .
    volumes:
      - data:/data
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.datecron.schedule: "@every 1d"

volumes:
  data:
