services:
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - plex-listen-brainz
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    labels:
      ofelia.job-local.my-test-job.schedule: "@every 5s"
      ofelia.job-local.my-test-job.command: "date"
      ofelia.job-run.listenbrainz.schedule: "@every 10m"
      ofelia.job-run.listenbrainz.command: "poetry run python main.py"
      ofelia.job-run.listenbrainz.volume: "/root/plex-listen-brainz-cron:/app"
      ofelia.job-run.listenbrainz.image: "ghcr.io/jcsumlin/plex-listen-brainz-cron/plex-listen-brainz-cron:latest"
      ofelia.job-run.listenbrainz.environment: '["LISTENBRAINZ_TOKEN=${LISTENBRAINZ_TOKEN}", "TAUTULLI_API_KEY=${TAUTULLI_API_KEY}", "TAUTULLI_URL=${TAUTULLI_URL}", "GOTIFY_URL=${GOTIFY_URL}", "GOTIFY_APP_TOKEN=${GOTIFY_APP_TOKEN}", "PLEX_USER=${PLEX_USER}"]'
      com.centurylinklabs.watchtower.enable: "true"

  plex-listen-brainz:
    image: ghcr.io/jcsumlin/plex-listen-brainz-cron/plex-listen-brainz-cron:latest
    env_file:
      - .env
    volumes:
      - /root/plex-listen-brainz-cron:/app
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_LABEL_ENABLE: "true"
