services:
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - plex-listen-brainz
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-local.my-test-job.schedule: "@every 5s"
      ofelia.job-local.my-test-job.command: "date"

  plex-listen-brainz:
    image: ghcr.io/jcsumlin/plex-listen-brainz-cron/plex-listen-brainz-cron:latest
    env_file:
      - .env
    volumes:
      - /root/plex-listen-brainz-cron:/data
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.listenbrainz.schedule: "@daily"
      ofelia.job-exec.listenbrainz.command: "poetry run python main.py"
